#!/bin/bash
# auto-ingest-session.sh — v7 execution layer 프로토타입
# 목적: 세션 jsonl을 요약 → mindvault에 ingest
#
# Usage: auto-ingest-session.sh <jsonl_path>
set -u

JSONL="${1:-}"
if [ -z "$JSONL" ] || [ ! -f "$JSONL" ]; then
    echo "Usage: auto-ingest-session.sh <session.jsonl>" >&2
    exit 1
fi

OUT_DIR="${HOME}/.cokacdir/workspace/obsidian-vault/30-Claude/31-Summaries"
mkdir -p "$OUT_DIR"

session_id=$(basename "$JSONL" .jsonl | cut -c1-8)
ts=$(date +%Y-%m-%d_%H%M)
outfile="$OUT_DIR/${ts}_cl_auto_${session_id}.md"

cat > "$outfile" <<MDEOF
---
date: $(date +%Y-%m-%d)
session_id: $session_id
agent: cl
type: summary
auto_generated: true
---

# Auto-ingest: $session_id

## Session stats
- jsonl: $JSONL
- size: $(ls -la "$JSONL" | awk '{print $5}') bytes

## Sample user turns (recent 3)
$(python3 -c "
import json
with open('$JSONL', 'r') as f:
    users = []
    for line in f:
        try: r = json.loads(line)
        except: continue
        if r.get('type') != 'user': continue
        msg = r.get('message', {})
        c = msg.get('content') if isinstance(msg, dict) else None
        if isinstance(c, list):
            text = '\n'.join(p.get('text','') if isinstance(p, dict) and p.get('type')=='text' else '' for p in c)
        else: text = str(c or '')[:200]
        users.append(text[:150])
    for u in users[-3:]:
        print(f'- {u.strip()}')
" 2>/dev/null)

(auto-generated by auto-ingest-session.sh)
MDEOF

echo "[OK] summary written: $outfile"
# mindvault ingest trigger (opt)
if command -v mindvault >/dev/null 2>&1; then
    cd "$(dirname "$outfile")" && mindvault ingest "$outfile" 2>&1 | tail -2
fi
